/* The Lucide glyphs the MSC database and the screens ask for, by name.

   The set is explicit rather than a dynamic lookup so the bundle only carries
   the icons that are actually drawn. Add a name here when a new msc_ row
   references one. */

import {
  Activity,
  ArrowRight,
  Bandage,
  BatteryLow,
  Brain,
  ThermometerSun,
  Utensils,
  Bed,
  Beer,
  Bike,
  Bot,
  CalendarDays,
  CalendarX,
  Camera,
  CloudOff,
  Check,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleQuestionMark,
  Clock,
  ClockAlert,
  Cookie,
  Database,
  Dot,
  Download,
  Dumbbell,
  Flame,
  FlaskConical,
  Footprints,
  Gauge,
  GitCommitHorizontal,
  Ham,
  HeartPulse,
  Info,
  Languages,
  Leaf,
  Link,
  Loader,
  LogOut,
  User,
  MessageSquareQuote,
  Moon,
  Mountain,
  Percent,
  Plane,
  Play,
  Pencil,
  Trash2,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  Route,
  Scale,
  Send,
  Settings,
  Sparkles,
  Sun,
  Tags,
  Target,
  Timer,
  TimerReset,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  WandSparkles,
  Waves,
  Wind,
  Wine,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'arrow-right': ArrowRight,
  'battery-low': BatteryLow,
  'bed': Bed,
  'beer': Beer,
  'bike': Bike,
  'bot': Bot,
  'calendar-days': CalendarDays,
  'calendar-x': CalendarX,
  'check': Check,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  // lucide renamed circle-help; the database still uses the old name.
  'circle-help': CircleQuestionMark,
  'clock': Clock,
  'clock-alert': ClockAlert,
  'cookie': Cookie,
  'database': Database,
  'dot': Dot,
  'download': Download,
  'dumbbell': Dumbbell,
  'flame': Flame,
  'flask-conical': FlaskConical,
  'footprints': Footprints,
  'gauge': Gauge,
  'git-commit-horizontal': GitCommitHorizontal,
  'ham': Ham,
  'heart-pulse': HeartPulse,
  'info': Info,
  'languages': Languages,
  'leaf': Leaf,
  'link': Link,
  'loader': Loader,
  'log-out': LogOut,
  'user': User,
  'message-square-quote': MessageSquareQuote,
  'moon': Moon,
  'mountain': Mountain,
  'percent': Percent,
  'plane': Plane,
  'play': Play,
  'pencil': Pencil,
  'plus': Plus,
  'trash-2': Trash2,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'rotate-ccw': RotateCcw,
  'route': Route,
  'camera': Camera,
  'cloud-off': CloudOff,
  'scale': Scale,
  'send': Send,
  'settings': Settings,
  'sparkles': Sparkles,
  'sun': Sun,
  'tags': Tags,
  'target': Target,
  'timer': Timer,
  'timer-reset': TimerReset,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'wand-sparkles': WandSparkles,
  'waves': Waves,
  'wind': Wind,
  'wine': Wine,
  /* le journal : ce qui a bloqué, et le motif « trop mangé » */
  'bandage': Bandage,
  'brain': Brain,
  'thermometer-sun': ThermometerSun,
  'utensils': Utensils,
  'zap': Zap,
};
